### logging
logging:
  level:
    root: INFO
    io.cuillgln: DEBUG
  path: logs  

### server
server:
  port: 8010
  servlet:
    context-path: 

### spring
spring:
#  datasource:
#    url: jdbc:mysql://172.20.182.211:3306/jtfile?characterEncoding=utf8&useSSL=false
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#  datasource:
#    url: jdbc:oracle:thin:@172.20.32.76:1521:ORCL
#    username: gdzr
#    password: gdzr
#    driver-class-name: oracle.jdbc.driver.OracleDriver
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://172.20.182.231:3306/bus_stop?characterEncoding=utf8&useSSL=false
      username: root
      password: root
      idle-timeout: 600000
      max-life-time: 1800000
      minimum-idle: 10
      maximum-pool-sie: 20
      validatation-timeout: 5000
  redis:
    host: localhost
    port: 6379
    # password: 123456
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

management:
  endpoints:
    web:
      exposure:
        include: "*"
    